version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./app/:/app/"
    command: uvicorn main:app --reload --host ${HOST}


  db:
    image: postgres:11.9-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
    driver: local
